---
# TODO: Fix https://github.com/phan/phan/issues/826
engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  fixme:
    enabled: false
  phpmd:
    enabled: true
    checks:
      # Phan has its own unused variable/parameter detection and variable patterns it ignores (e.g. $_)
      UnusedFormalParameter:
        enabled: false
      UnusedLocalVariable:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      # Phan uses $snake_case
      Controversial/CamelCaseVariableName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
  phan:
    enabled: false
    config:
        file_extensions: "php"
        ignore-undeclared: false
        quick: false
        backward-compatibility-checks: true
        dead-code-detection: true
ratings:
  paths:
    - "**.php"
exclude_paths:
  - tests/**/*
