language: php

php:
  - 7

env:
  - TEST_SUITE="AnalyzerTest"
  - TEST_SUITE="PhanTest"
  - TEST_SUITE="RasmusTest"
  - TEST_SUITE="LanguageTest"
  - TEST_SUITE="OutputPrinterTest"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - ./tests/setup.sh
  - composer validate

install:
  - composer --prefer-source install

script:
  - ./vendor/bin/phpunit --colors --testsuite "$TEST_SUITE"
